In [1]:
#read data
import pandas as pd
import numpy as np

path = "./data/data1.xlsx"

excel_data_df = pd.read_excel(path, sheet_name='Sheet1')

# print whole sheet data
print(excel_data_df)





          A  B         C
0       0.0  1  1.000000
1       0.0  1  1.000000
2       0.0  1  1.000000
3       0.0  1  1.000000
4       0.0  1  1.000000
...     ... ..       ...
430204  0.0  1  0.131771
430205  0.0  1  0.131771
430206  0.0  1  0.131771
430207  0.0  1  0.131771
430208  0.0  1  0.131771

[430209 rows x 3 columns]


In [14]:
#plot first data
# from matplotlib import pyplot as plt
# plt.figure(figsize=(16,8))
# plt.title(f'{symbol} :')
# plt.plot(df['Close'])
# plt.xlabel('Date' , fontsize = 18)
# plt.ylabel('Price' , fontsize = 18)
# plt.show()



#prepare data

x_data = excel_data_df.filter(['A'])
x_data = x_data.values

y_data = excel_data_df.filter(['C'])
y_data = y_data.values

x_min = x_data.min()
x_max = x_data.max()

y_min = y_data.min()
y_max = y_data.max()


x_data = (x_data-x_min)/(x_max -x_min)
y_data = (y_data-y_min)/(y_max -y_min)


x_data

array([[0.49711787],
       [0.49711787],
       [0.49711787],
       ...,
       [0.49711787],
       [0.49711787],
       [0.49711787]])

In [17]:
#train data
percentage = .7
train_count = int( len(x_data) *percentage)

x_train = x_data[:train_count]
y_train = y_data[:train_count]

x_train

array([[0.49711787],
       [0.49711787],
       [0.49711787],
       ...,
       [0.49711787],
       [0.49711787],
       [0.49711787]])

In [20]:
#Build model
from keras.models import  Sequential, load_model
from keras.layers import Dense,LSTM,Dropout
from datetime import datetime
import json
from pathlib import Path
from dateutil import parser


model = Sequential()
model.add(Dense(50, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1))
model.compile(optimizer = 'adam' , loss="mse")


In [21]:
model.fit(x_train, y_train, batch_size=1, epochs=1 )

133307/301146 [============>.................] - ETA: 5:29 - loss: 0.0552

KeyboardInterrupt: 

In [22]:
x_predict = x_data[train_count:]
y_predict = y_data[train_count:]


prediction = model.predict(x_predict)

prediction = prediction *(y_max-y_min) +y_min
y_predict = y_predict *(y_max-y_min) +y_min


print(prediction)
print(y_predict)

4034/4034 [==============================] - 7s 2ms/step
[[0.6085068]
 [0.6085068]
 [0.6085068]
 ...
 [0.6085068]
 [0.6085068]
 [0.6085068]]
[[0.2968959 ]
 [0.2968959 ]
 [0.2968959 ]
 ...
 [0.13177122]
 [0.13177122]
 [0.13177122]]
