In [1]:
#read data
import pandas as pd
import numpy as np

path = "./data/data2.xlsx"

excel_data_df = pd.read_excel(path, sheet_name='Sheet1')

# print whole sheet data
print(excel_data_df)





         I1            I2            I3   I4      I5        I6          I7  \
0       0.1  2.000000e-08  1.000000e-08  1.5  0.0000  0.019960  258.890320   
1       0.1  2.000000e-08  1.000000e-08  1.5  0.5031  0.019961  258.735884   
2       0.1  2.000000e-08  1.000000e-08  1.5  0.5031  0.019958  259.401591   
3       0.1  2.000000e-08  1.000000e-08  1.5  0.5031  0.019959  259.329431   
4       0.1  2.000000e-08  1.000000e-08  1.5  0.5031  0.019958  259.471893   
...     ...           ...           ...  ...     ...       ...         ...   
132877  0.1  2.000000e-08  1.000000e-08  1.5  0.0678  0.020411  342.096155   
132878  0.1  2.000000e-08  1.000000e-08  1.5  0.0678  0.020414  342.141950   
132879  0.1  2.000000e-08  1.000000e-08  1.5  0.0678  0.020415  342.156787   
132880  0.1  2.000000e-08  1.000000e-08  1.5  0.0678  0.020415  342.156448   
132881  0.1  2.000000e-08  1.000000e-08  1.5  0.0678  0.020414  342.139711   

               O  
0       1.000000  
1       1.000076  
2     

In [24]:
#prepare data
n_min = excel_data_df.min().min()
n_max = excel_data_df.max().max()


x_data = excel_data_df.filter(['I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7'])
x_data = x_data.values

y_data = excel_data_df.filter(['O'])
y_data = y_data.values







# x_data = (x_data-n_min)/(n_max -n_min)
# y_data = (y_data-n_min)/(n_max -n_min)


x_data

array([[1.00000000e-01, 2.00000000e-08, 1.00000000e-08, ...,
        0.00000000e+00, 1.99600000e-02, 2.58890320e+02],
       [1.00000000e-01, 2.00000000e-08, 1.00000000e-08, ...,
        5.03100000e-01, 1.99605251e-02, 2.58735884e+02],
       [1.00000000e-01, 2.00000000e-08, 1.00000000e-08, ...,
        5.03100000e-01, 1.99582936e-02, 2.59401591e+02],
       ...,
       [1.00000000e-01, 2.00000000e-08, 1.00000000e-08, ...,
        6.78000000e-02, 2.04147042e-02, 3.42156787e+02],
       [1.00000000e-01, 2.00000000e-08, 1.00000000e-08, ...,
        6.78000000e-02, 2.04146818e-02, 3.42156448e+02],
       [1.00000000e-01, 2.00000000e-08, 1.00000000e-08, ...,
        6.78000000e-02, 2.04135779e-02, 3.42139711e+02]])

In [25]:
#train data
percentage = .8
train_count = int( len(x_data) *percentage)

x_train = x_data[:train_count]
y_train = y_data[:train_count]

x_train.shape
y_train.shape

(106305, 1)

In [33]:
#Build model
from keras.models import  Sequential, load_model
from keras.layers import Dense,LSTM,Dropout
from datetime import datetime
import json
from pathlib import Path
from dateutil import parser


model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(7,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1))
model.compile(optimizer = 'adam' , loss="mse")


In [46]:
model.fit(x_train, y_train, batch_size=1, epochs=1 )

Epoch 1/2
 82565/106305 [======================>.......] - ETA: 41s - loss: 0.0228

KeyboardInterrupt: 

In [48]:
x_predict = x_data[train_count:]
y_predict = y_data[train_count:]


prediction = model.predict(x_predict)

# prediction = prediction *(n_max-n_min) +n_min
# y_predict = y_predict *(n_max-n_min) +n_min


print(prediction)
print('______________')
print(y_predict)


831/831 [==============================] - 2s 2ms/step
[[0.59744805]
 [0.5974147 ]
 [0.5973587 ]
 ...
 [0.5290852 ]
 [0.52908665]
 [0.52915794]]
______________
[[0.27369577]
 [0.27374978]
 [0.27384028]
 ...
 [0.09372901]
 [0.09372721]
 [0.09363857]]
